"""add render pipeline columns

Revision ID: 113e432c4971
Revises: 3e334841463e
Create Date: 2026-03-13 12:06:05.773881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '113e432c4971'
down_revision: Union[str, None] = '3e334841463e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('face_track', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exports', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('exports', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'exports', 'jobs', ['job_id'], ['id'])
    op.add_column('jobs', sa.Column('render_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'render_context')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_column('exports', 'status')
    op.drop_column('exports', 'job_id')
    op.drop_column('clips', 'face_track')
    # ### end Alembic commands ###
