"""add billing columns to users

Revision ID: bc8026f01304
Revises: 113e432c4971
Create Date: 2026-03-13 19:03:41.931211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8026f01304'
down_revision: Union[str, None] = '113e432c4971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=20), nullable=False, server_default='free'))
    op.add_column('users', sa.Column('subscription_stripe_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('period_exports_used', sa.Integer(), nullable=False, server_default='0'))
    op.create_unique_constraint('uq_users_stripe_customer_id', 'users', ['stripe_customer_id'])
    op.create_check_constraint(
        'ck_users_subscription_tier',
        'users',
        "subscription_tier IN ('free', 'starter', 'pro')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_subscription_tier', 'users', type_='check')
    op.drop_constraint('uq_users_stripe_customer_id', 'users', type_='unique')
    op.drop_column('users', 'period_exports_used')
    op.drop_column('users', 'current_period_end')
    op.drop_column('users', 'subscription_stripe_id')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
